name: Generate MISTRAL-PYTHON-SDK-GOOGLE-CLOUD
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: optionally set a specific SDK version
        type: string
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: ${{ github.event.inputs.force }}
      mode: pr
      # We need poetry < 2.0 to avoid the speakeasy run failure.
      # This was fixed in speakasy v1.467.0 but we're locked at 1.462.2 waiting for other speakeasy fixes.
      poetry_version: 1.8.5
      set_version: ${{ github.event.inputs.set_version }}
      speakeasy_version: latest
      target: mistral-python-sdk-google-cloud
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      pypi_token: ${{ secrets.PYPI_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
